//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaroGame.Resources.locale
{
  using System;


  /// <summary>
  ///   A strongly-typed resource class, for looking up localized strings, etc.
  /// </summary>
  // This class was auto-generated by the StronglyTypedResourceBuilder
  // class via a tool like ResGen or Visual Studio.
  // To add or remove a member, edit your .ResX file then rerun ResGen
  // with the /str option, or rebuild your VS project.
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  internal class vi
  {

    private static global::System.Resources.ResourceManager resourceMan;

    private static global::System.Globalization.CultureInfo resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal vi()
    {
    }

    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager
    {
      get
      {
        if (object.ReferenceEquals(resourceMan, null))
        {
          global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CaroGame.Resources.locale.vi", typeof(vi).Assembly);
          resourceMan = temp;
        }
        return resourceMan;
      }
    }

    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture
    {
      get
      {
        return resourceCulture;
      }
      set
      {
        resourceCulture = value;
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Giới thiệu.
    /// </summary>
    internal static string about
    {
      get
      {
        return ResourceManager.GetString("about", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Thêm.
    /// </summary>
    internal static string add
    {
      get
      {
        return ResourceManager.GetString("add", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Người với máy.
    /// </summary>
    internal static string aiMode
    {
      get
      {
        return ResourceManager.GetString("aiMode", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Giao diện.
    /// </summary>
    internal static string appearance
    {
      get
      {
        return ResourceManager.GetString("appearance", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Cài đặt giao diện.
    /// </summary>
    internal static string appearanceSetting
    {
      get
      {
        return ResourceManager.GetString("appearanceSetting", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Quay lại.
    /// </summary>
    internal static string back
    {
      get
      {
        return ResourceManager.GetString("back", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Hủy.
    /// </summary>
    internal static string cancel
    {
      get
      {
        return ResourceManager.GetString("cancel", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Caro.
    /// </summary>
    internal static string caro
    {
      get
      {
        return ResourceManager.GetString("caro", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Quốc gia.
    /// </summary>
    internal static string country
    {
      get
      {
        return ResourceManager.GetString("country", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Lập trình viên.
    /// </summary>
    internal static string developer
    {
      get
      {
        return ResourceManager.GetString("developer", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Bạn có chắc muốn thoát khỏi trò chơi?.
    /// </summary>
    internal static string exitMessage
    {
      get
      {
        return ResourceManager.GetString("exitMessage", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Chế độ chơi.
    /// </summary>
    internal static string gameMode
    {
      get
      {
        return ResourceManager.GetString("gameMode", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Hướng dẫn.
    /// </summary>
    internal static string guide
    {
      get
      {
        return ResourceManager.GetString("guide", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Lỗi.
    /// </summary>
    internal static string invalid
    {
      get
      {
        return ResourceManager.GetString("invalid", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Ngôn ngữ.
    /// </summary>
    internal static string language
    {
      get
      {
        return ResourceManager.GetString("language", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Cài đặt ngôn ngữ.
    /// </summary>
    internal static string languageSetting
    {
      get
      {
        return ResourceManager.GetString("languageSetting", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Kết nối mạng LAN.
    /// </summary>
    internal static string lanMode
    {
      get
      {
        return ResourceManager.GetString("lanMode", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Tải game đã lưu.
    /// </summary>
    internal static string loadGame
    {
      get
      {
        return ResourceManager.GetString("loadGame", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Game Mới.
    /// </summary>
    internal static string newGame
    {
      get
      {
        return ResourceManager.GetString("newGame", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Tiếp.
    /// </summary>
    internal static string next
    {
      get
      {
        return ResourceManager.GetString("next", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Không có dữ liệu.
    /// </summary>
    internal static string nothingMessage
    {
      get
      {
        return ResourceManager.GetString("nothingMessage", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Hoặc.
    /// </summary>
    internal static string or
    {
      get
      {
        return ResourceManager.GetString("or", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Tổng quan.
    /// </summary>
    internal static string overview
    {
      get
      {
        return ResourceManager.GetString("overview", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Người chơi.
    /// </summary>
    internal static string player
    {
      get
      {
        return ResourceManager.GetString("player", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Người chơi đầu tiên.
    /// </summary>
    internal static string player1
    {
      get
      {
        return ResourceManager.GetString("player1", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Người chơi thứ hai.
    /// </summary>
    internal static string player2
    {
      get
      {
        return ResourceManager.GetString("player2", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Cài đặt người chơi.
    /// </summary>
    internal static string playerSetting
    {
      get
      {
        return ResourceManager.GetString("playerSetting", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Hoàn tác.
    /// </summary>
    internal static string redo
    {
      get
      {
        return ResourceManager.GetString("redo", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Xóa.
    /// </summary>
    internal static string remove
    {
      get
      {
        return ResourceManager.GetString("remove", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Đặt lại.
    /// </summary>
    internal static string reset
    {
      get
      {
        return ResourceManager.GetString("reset", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Lưu.
    /// </summary>
    internal static string save
    {
      get
      {
        return ResourceManager.GetString("save", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Lưu game.
    /// </summary>
    internal static string saveGame
    {
      get
      {
        return ResourceManager.GetString("saveGame", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Cài đặt.
    /// </summary>
    internal static string setting
    {
      get
      {
        return ResourceManager.GetString("setting", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Kích thức.
    /// </summary>
    internal static string sizeBoard
    {
      get
      {
        return ResourceManager.GetString("sizeBoard", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Cài đặt kích thức.
    /// </summary>
    internal static string sizeSetting
    {
      get
      {
        return ResourceManager.GetString("sizeSetting", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Âm thanh.
    /// </summary>
    internal static string sound
    {
      get
      {
        return ResourceManager.GetString("sound", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Cài đặt âm thanh.
    /// </summary>
    internal static string soundSetting
    {
      get
      {
        return ResourceManager.GetString("soundSetting", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Thời gian.
    /// </summary>
    internal static string time
    {
      get
      {
        return ResourceManager.GetString("time", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Cài đặt thời gian.
    /// </summary>
    internal static string timeSetting
    {
      get
      {
        return ResourceManager.GetString("timeSetting", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Hai người chơi.
    /// </summary>
    internal static string twoPlayerMode
    {
      get
      {
        return ResourceManager.GetString("twoPlayerMode", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Quay lại.
    /// </summary>
    internal static string undo
    {
      get
      {
        return ResourceManager.GetString("undo", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Phiên bản.
    /// </summary>
    internal static string version
    {
      get
      {
        return ResourceManager.GetString("version", resourceCulture);
      }
    }
  }
}
